// Generated from hola.txt (canonical list)
export const FRANCHISE_NAME_MAP = {
  "kfc": "KFC",
  "subway": "SUBWAY",
  "buffalo-waffles": "BUFFALO WAFFLES",
  "buffet-express": "BUFFET EXPRESS",
  "burger-king": "BURGER KING",
  "cest-si-bon": "CEST SI BON",
  "casta": "CASTAÑO",
  "chilias": "CHILIÂ´S",
  "doggis": "DOGGIS",
  "domino": "DOMINO",
  "dunkin-donuts": "DUNKIN' DONUTS",
  "elkika-ilmenau": "ELKIKA ILMENAU",
  "emporio-la-rosa": "EMPORIO LA ROSA",
  "fork": "FORK",
  "fries-and-bites": "FRIES AND BITES",
  "little-caesar": "LITTLE CAESAR",
  "mc-donald-s": "MC DONALD'S",
  "paradiso": "PARADISO",
  "sakura-express": "SAKURA EXPRESS",
  "san-camilo": "SAN CAMILO",
  "starbucks": "STARBUCKS",
  "tarragona": "TARRAGONA",
  "tommy-beans": "TOMMY BEANS",
  "buffalo-beef": "BUFFALO BEEF",
  "bobibobi": "BOBIBOBI",
  "alvi": "ALVI",
  "achoclonados": "ACHOCLONADOS",
  "china-wok": "CHINA WOK",
  "chilis": "CHILIS",
  "hay-partes-de-chili-s-que-quedaron-fuera-porque-estaban-escritos-como-chilis": "(hay partes de CHILI'S que quedaron fuera porque estaban escritos como CHILIS)",
  "erbi": "ERBI",
  "happy-day-waffles": "HAPPY DAY WAFFLES",
  "juan-maestro": "JUAN MAESTRO",
  "jumbo": "JUMBO",
  "latin-pizza": "LATIN PIZZA",
  "lider-acuenta": "LIDER ACUENTA",
  "lider-express": "LIDER EXPRESS",
  "lider": "LIDER",
  "maisi": "MAISI",
  "mamut": "MAMUT",
  "maxik": "MAXIK",
  "nurys": "NURYS",
  "okm": "OKM",
  "oxxo": "OXXO",
  "pedro-juan-y-diego": "PEDRO JUAN Y DIEGO",
  "piwen": "PIWEN",
  "pizza-pizza": "PIZZA PIZZA",
  "pollo-stop": "POLLO STOP",
  "rikas": "RIKAS",
  "s10": "S10",
  "santa-isabel": "SANTA ISABEL",
  "savory": "SAVORY",
  "spid": "SPID",
  "stop-cafe": "STOP CAFE",
  "sushi-blues": "SUSHI BLUES",
  "taco-bell": "TACO BELL",
  "unimarc": "UNIMARC",
  "wendys": "WENDYS",
  "xs": "XS"
};
