// Map franchise tokens (normalized keys) to official websites.
// Edit this file to add/update websites. If a token is not present,
// the UI will fall back to a Google search for the brand name.
export const WEBSITE_MAP = {
  // Rellena las URLs oficiales aquí. Si dejas vacío, se usará búsqueda Google.
  'kfc': 'https://www.kfc.cl',
  'subway': 'https://www.subway.com/es-CL',
  'buffalo-waffles': 'https://www.buffalowaffles.cl',
  'buffet-express': 'https://buffetexpress.cl/',
  'burger-king': 'https://www.burgerking.cl',
  'cest-si-bon': 'https://www.instagram.com/cestsibon_cl/?hl=es',
  'casta': 'https://www.castano.cl',
  'chilias': 'https://www.chilis.cl',
  'doggis': 'https://www.doggis.cl',
  'domino': 'https://www.dominos.cl',
  'dunkin-donuts': 'https://www.dunkin.cl',
  'elkika-ilmenau': 'https://www.elkika.cl/',
  'emporio-la-rosa': 'https://www.emporiolarosa.cl',
  'fork': 'https://www.forkchile.cl',
  'fries-and-bites': 'https://www.friesandbites.cl/',
  'little-caesar': 'https://www.littlecaesars.cl',
  'mc-donald-s': 'https://www.mcdonalds.cl',
  'paradiso': 'https://www.paradiso.cl/pedir',
  'sakura-express': 'https://sakuraexpress.cl/sakura/home',
  'san-camilo': 'https://www.sancamilo.cl',
  'starbucks': 'https://www.starbucks.cl',
  'tarragona': 'https://www.tarragona.cl',
  'tommy-beans': 'https://www.tommybeans.cl',
  'buffalo-beef': 'https://www.instagram.com/bufalobeef/?hl=es',
  'bobibobi': 'https://www.bobibobi.cl',
  'alvi': 'https://www.alvi.cl',
  'achoclonados': 'https://www.achoclonados.cl/',
  // Hasta confirmar dominio oficial, dejamos búsqueda dirigida en Google
  'china-wok': 'https://www.chinawok.cl/pedir?utm_source=GoogleAds&utm_medium=search&utm_campaign=Trafico&gad_source=1&gad_campaignid=23201521350&gbraid=0AAAAApJjfbjvIE3zCGIf5EEUAKZapbops&gclid=Cj0KCQiAiebIBhDmARIsAE8PGNKlZWENB7dVto7zzl_w42HrFkgWdJWro1TCZ2Znp-kxtIOrfV4VOSwaAphnEALw_wcB',
  'chilis': 'https://www.chilis.cl/',
  // nota: se omite la clave larga explicativa de chilis
  'erbi': 'https://www.instagram.com/erbi.supermercados/?hl=es',
  'happy-day-waffles': 'https://happydayswaffles.cl/',
  'juan-maestro': 'https://www.juanmaestro.cl',
  'jumbo': 'https://www.jumbo.cl',
  'latin-pizza': 'https://www.latinpizza.cl/',
  'lider-acuenta': 'https://www.acuenta.cl',
  'lider-express': 'https://www.lider.cl',
  'lider': 'https://www.lider.cl',
  'maisi': '',
  'mamut': 'https://www.mamut.cl',
  'maxik': 'https://www.instagram.com/maxik_cl/?hl=es-la',
  'nurys': 'https://wenalascabras.wordpress.com/2018/09/03/cafeterias-nurys/',
  'okm': '',
  'oxxo': 'https://www.oxxo.cl',
  'pedro-juan-y-diego': 'https://www.instagram.com/pjdchile/?hl=es',
  'piwen': 'https://www.piwen.cl/?srsltid=AfmBOop_ZsmPN92IJ3t-kayyIpUFSqV0DE1mY9ZCBReu0FYi3vrlpmEI',
  'pizza-pizza': 'https://www.pizzapizza.cl/',
  'pollo-stop': 'https://www.pollostop.cl',
  'rikas': 'https://www.instagram.com/rikaspapashot/',
  's10': 'https://www.super10.cl/',
  'santa-isabel': 'https://www.santaisabel.cl',
  'savory': 'https://www.savory.cl',
  'spid': 'https://www.spid.cl',
  'stop-cafe': 'https://www.google.com/search?q=stop+cafe+chile+sitio+oficial',
  'sushi-blues': 'https://www.google.com/search?q=sushi+blues+chile+sitio+oficial',
  'taco-bell': 'https://www.tacobell.cl',
  'unimarc': 'https://www.unimarc.cl',
  'wendys': 'https://www.wendys.cl/?srsltid=AfmBOoop1qsj6X4czq4WPmpe9fsppJIpAGnwSfmkz1tc7uqrvrGKjX1g',
  'xs': 'https://www.instagram.com/xsmarketchile/?hl=es'
};
