// Map franchise tokens (normalized keys) to official websites.
// Edit this file to add/update websites. If a token is not present,
// the UI will fall back to a Google search for the brand name.
export const WEBSITE_MAP = {
  // Rellena las URLs oficiales aquí. Si dejas vacío, se usará búsqueda Google.
  'kfc': 'https://www.kfc.cl',
  'subway': 'https://www.subway.com/es-CL',
  'buffalo-waffles': 'https://www.buffalowaffles.cl',
  'buffet-express': '',
  'burger-king': 'https://www.burgerking.cl',
  'cest-si-bon': '',
  'casta': 'https://www.castano.cl',
  'chilias': 'https://www.chilis.cl',
  'doggis': 'https://www.doggis.cl',
  'domino': 'https://www.dominos.cl',
  'dunkin-donuts': 'https://www.dunkin.cl',
  'elkika-ilmenau': '',
  'emporio-la-rosa': 'https://www.emporiolarosa.cl',
  'fork': 'https://www.forkchile.cl',
  'fries-and-bites': '',
  'little-caesar': 'https://www.littlecaesars.cl',
  'mc-donald-s': 'https://www.mcdonalds.cl',
  'paradiso': '',
  'sakura-express': '',
  'san-camilo': 'https://www.sancamilo.cl',
  'starbucks': 'https://www.starbucks.cl',
  'tarragona': 'https://www.tarragona.cl',
  'tommy-beans': 'https://www.tommybeans.cl',
  'buffalo-beef': '',
  'bobibobi': 'https://www.bobibobi.cl',
  'alvi': 'https://www.alvi.cl',
  'achoclonados': '',
  // Hasta confirmar dominio oficial, dejamos búsqueda dirigida en Google
  'china-wok': 'https://www.google.com/search?q=china+wok+chile+sitio+oficial',
  'chilis': '',
  // nota: se omite la clave larga explicativa de chilis
  'erbi': '',
  'happy-day-waffles': '',
  'juan-maestro': 'https://www.juanmaestro.cl',
  'jumbo': 'https://www.jumbo.cl',
  'latin-pizza': '',
  'lider-acuenta': 'https://www.acuenta.cl',
  'lider-express': 'https://www.lider.cl',
  'lider': 'https://www.lider.cl',
  'maisi': '',
  'mamut': 'https://www.mamut.cl',
  'maxik': '',
  'nurys': '',
  'okm': '',
  'oxxo': 'https://www.oxxo.cl',
  'pedro-juan-y-diego': 'https://www.pedrojuanydiego.cl',
  'piwen': '',
  'pizza-pizza': '',
  'pollo-stop': 'https://www.pollostop.cl',
  'rikas': '',
  's10': '',
  'santa-isabel': 'https://www.santaisabel.cl',
  'savory': 'https://www.savory.cl',
  'spid': 'https://www.spid.cl',
  'stop-cafe': 'https://www.google.com/search?q=stop+cafe+chile+sitio+oficial',
  'sushi-blues': 'https://www.google.com/search?q=sushi+blues+chile+sitio+oficial',
  'taco-bell': 'https://www.tacobell.cl',
  'unimarc': 'https://www.unimarc.cl',
  'wendys': '',
  'xs': ''
};
